### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twQ103_2122-consigue-acertar#1]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by maikadelsol** [comment]
#include <stdio.h>
int main(){
	int nombre, opcion;
	
	printf ("dime tu nombre:\n");
	scanf ("%f", &nombre);
	
	fflush (stdin);
	
	printf ("introduce una opcion:\n");
	printf ("a-jugar\n");
	printf ("b- ver historial de jugadores\n");
	printf ("c- ver ranking de jugadores\n");
	scanf ("%c", &opcion);
	
	if (opcion == 'a'){
		printf ("el juego\n");
	}
	else if (opcion == 'b'){
		printf ("ver el historial\n");
	}
	else if (opcion == 'c'){
		printf ("ranking \n");
	}
	else{
		printf ("error\n");
	}

}
